name: Basic Tests

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: clone submodules
      run: git submodule update --init --recursive
    - name: install valgrind
      run: sudo apt install valgrind
    - name: make test
      run: make test
